# -*- coding: utf-8 -*-
"""data_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7tQ_5oNGK4okSjRMM04V9gowPMcqKen
"""

from datetime import datetime, timedelta
import numpy as np
import pandas as pd

np.random.seed(42)

# Configurações gerais
total_carrinhos = 2600  # ~91.000 pacotes (35 pacotes por carrinho)
itens_por_carrinho = 35
data_inicio = datetime(2026, 8, 1, 6, 0, 0)

# 1. GERANDO TABELA REBIN
carrinhos_id = [f"CAR-{i:05d}" for i in range(1, total_carrinhos + 1)]
rebin_inicio = [
    data_inicio + timedelta(seconds=int(x))
    for x in np.sort(
        np.random.randint(0, 30 * 24 * 3600, total_carrinhos)
    )
]
rebin_duracao = np.random.normal(loc=12, scale=2, size=total_carrinhos).round(2)

df_rebin = pd.DataFrame(
    {
        "id_carrinho": carrinhos_id,
        "id_op_rebin": np.random.choice(
            [f"OP-REB-{i:02d}" for i in range(1, 10)], total_carrinhos
        ),
        "linha_rebin": np.random.choice(["L01", "L02"], total_carrinhos),
        "dt_inicio_montagem": rebin_inicio,
        "tempo_montagem_min": rebin_duracao,
    }
)

df_rebin["dt_fim_montagem"] = df_rebin.apply(
    lambda r: r["dt_inicio_montagem"]
    + timedelta(minutes=r["tempo_montagem_min"]),
    axis=1,
)

# 2. GERANDO TABELA PACK
pacotes_list = []
for idx, row in df_rebin.iterrows():
    # Tempo entre o Rebin e a bancada de Pack
    inicio_pack = row["dt_fim_montagem"] + timedelta(
        minutes=float(np.random.uniform(2, 8))
    )
    # Meta de ciclo (15-20 min por carrinho)
    tempo_pack_carrinho = float(np.random.normal(loc=17, scale=3))

    for item in range(1, itens_por_carrinho + 1):
        pacote_id = f"PKT-{idx*35 + item:07d}"
        fim_pack = inicio_pack + timedelta(
            minutes=tempo_pack_carrinho * (item / 35)
        )
        bancada_id = f"L0{np.random.choice([1,2])}-B{np.random.randint(1,15):02d}"

        pacotes_list.append(
            {
                "id_pacote": pacote_id,
                "id_carrinho": row["id_carrinho"],
                "id_bancada": bancada_id,
                "id_op_pack": f"OP-PCK-{np.random.randint(1,25):02d}",
                "dt_inicio_pack": inicio_pack,
                "dt_fim_pack": fim_pack,
                "tempo_ciclo_carrinho_min": round(tempo_pack_carrinho, 2),
            }
        )

df_pack = pd.DataFrame(pacotes_list)

# 3. GERANDO TABELA SLAM (BALANÇA)
slam_list = []
for idx, row in df_pack.iterrows():
    dt_pesagem = row["dt_fim_pack"] + timedelta(
        seconds=float(np.random.uniform(10, 90))
    )
    status = np.random.choice(
        ["Aprovado", "Rejeitado"], p=[0.96, 0.04]
    )  # 4% de rejeite na balança

    slam_list.append(
        {
            "id_pacote": row["id_pacote"],
            "id_op_balanca": f"OP-BAL-{np.random.randint(1,4):02d}",
            "dt_pesagem": dt_pesagem,
            "status_balanca": status,
        }
    )

df_slam = pd.DataFrame(slam_list)

# SALVANDO OS ARQUIVOS CSV
df_rebin.to_csv("tb_rebin.csv", index=False)
df_pack.to_csv("tb_pack.csv", index=False)
df_slam.to_csv("tb_slam.csv", index=False)

print(f"Bases geradas com sucesso!")
print(f"Tabela Rebin: {len(df_rebin)} carrinhos")
print(f"Tabela Pack: {len(df_pack)} pacotes")
print(f"Tabela SLAM: {len(df_slam)} leituras de balança")